### ISSUE TITLE
Problem on ubuntu 18.04

### ISSUE THREAD

**Issue by xguya** [webchain-network/webchain-wallet#1]
Unable to download Webchaind: Error: EACCES: permission denied, open '/opt/WebchainWallet/resources/webchaind'

**Comment by RonaldEAM** [comment]
@xguya Try running as root, `sudo webchainwallet`

**Comment by xguya** [comment]
Solved

**Comment by xipheCom** [comment]
Excuse me if that is not the correct place to discuss this but.... why do you need root access? This issue is not solved! it is just a dangerous and unusual workaround. webchainwallet can do EVERYTHING with your system if you do it this way. Changing password, installing bots, send emails,...

even if we can trust webchainwallet. If it has a security break you open your complete system for this security break.

A better way is to change the folder `webchaind` wallet to a special group and give this group read/write access to this folder and add your user to this group. Or just change the owner of the folder to your user account. Or give the folder write access for everyone, not only root. This should made from the installation routine.

But do not run an application as root when there is no need to do!!!
