### ISSUE TITLE
Can't open wallet on kali 2018.2

### ISSUE THREAD

**Issue by oyekanwahab** [webchain-network/webchain-wallet#3]
[log.log](https://github.com/webchain-network/webchain-wallet/files/2129918/log.log)
Attach is the log file

Can't get the wallet to start

**Comment by albertodelgadog** [comment]
Hello! The wallet seems not to be compatible with this linux version due to the error `error` while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`. 

We will consider packing this library for future versions. We highly invite you to join discord https://discord.gg/GMbHpF3 for real-time communication.

**Comment by tendo-abc** [comment]
Hello, is this issue still actual on our latest wallet https://github.com/webchain-network/webchain-wallet/releases ?

**Comment by danielwebimp** [comment]
This has been fixed in the new release. You can simply download AppImage file http://joxi.ru/YmE6qKxHwYQlE2 . In properties, set allow to execute then run it and it should work.
