### ISSUE TITLE
Failed to fetch when clicking on MainNet Full node on latest update 1.0.0

### ISSUE THREAD

**Issue by tyler81294** [webchain-network/webchain-wallet#6]
``` 
TypeError: Failed to fetch 
 While processing action: 
 function (dispatch, getState, api) {
    return api.geth.eth.getSyncing().then(function (result) {
      if ((typeof result === 'undefined' ? 'undefined' : _typeof(result)) === 'object') {
        return dispatch({
          type: _actionTypes2.default.SYNCING,
          syncing: true,
          status: result
        });
      }

      dispatch({
        type: _actionTypes2.default.SYNCING,
        syncing: false
      });
    });
  }
 ```

**Comment by HaydenJayAylor** [comment]
I am having the exact same error thrown at me.  Sometimes it works if I reinstall it.  But that doesn't last long.

**Comment by tendo-abc** [comment]
Hello is it still a problem, have tried using `MainNet node 1` ?

**Comment by danielwebimp** [comment]
If you've selected full node during the installation of the wallet, the whole blockchain of Webchain is downloaded to your computer and it takes time and resources to be completed. Please instead of selecting Full Node, better use Remote Node 1 or 2 . Also make sure to open the port in your firewall to authorize your wallet to connect to Webchain Network.
