### ISSUE TITLE
Extreme processor load

### ISSUE THREAD

**Issue by Foxxite** [webchain-network/webchain-wallet#74]
Software uses 50% of processor and keeps going up.
(On AMD Ryzen 7 1800X)

**Comment by danielwebimp** [comment]
> Software uses 50% of processor and keeps going up.
> (On AMD Ryzen 7 1800X)

It's normal because if you've selected full node during the installation of the wallet, the whole blockchain of Webchain is downloaded to your computer and it takes time and resources to be completed. So, instead of selecting Full Node, better use Remote Node 1 or 2 and you will not face this issue.
